# Site settings
title: Christer's Ramblings
email: christer@weinigel.se
description: > # this means to ignore newlines until "baseurl:"
  Random stuff from the fingers of Christer Weinigel.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.weinigel.se" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: wingel

gems:
  - jekyll-feed

# Build settings
markdown: kramdown
